-- Update students table to match CSV columns
ALTER TABLE students 
ADD COLUMN IF NOT EXISTS grn_no VARCHAR(50),
ADD COLUMN IF NOT EXISTS first_name VARCHAR(100),
ADD COLUMN IF NOT EXISTS middle_name VARCHAR(100),
ADD COLUMN IF NOT EXISTS last_name VARCHAR(100),
ADD COLUMN IF NOT EXISTS mothers_name VARCHAR(100),
ADD COLUMN IF NOT EXISTS student_mobile VARCHAR(20),
ADD COLUMN IF NOT EXISTS parents_mobile VARCHAR(20),
ADD COLUMN IF NOT EXISTS faculty VARCHAR(100),
ADD COLUMN IF NOT EXISTS samiti_year INT,
ADD COLUMN IF NOT EXISTS college_year INT,
ADD COLUMN IF NOT EXISTS course_duration INT,
ADD COLUMN IF NOT EXISTS hostel_allocation VARCHAR(100),
ADD COLUMN IF NOT EXISTS wing VARCHAR(50),
ADD COLUMN IF NOT EXISTS floor VARCHAR(20),
ADD COLUMN IF NOT EXISTS room_number VARCHAR(20);